import bcrypt from 'bcryptjs';
import {backupTickets,TABLES,stateDigest} from './backup.js';
export const DELETE_ORDER=['fleet_inspection_photos','fleet_reservation_events','fleet_inspections','fleet_reservations','maintenance','fuel_records','notifications','drivers','vehicles','yards'];
export async function cleanRecords(c,org,user){for(const t of DELETE_ORDER)await c.query(`DELETE FROM public.${t} WHERE organization_id=$1`,[org]);await c.query('DELETE FROM users WHERE organization_id=$1 AND id<>$2',[org,user]);await c.query("UPDATE organization_settings SET revision=revision+1,details=details-'dismissedAlerts',updated_at=NOW() WHERE organization_id=$1",[org]);}
export function installCleanup(app,{pool,auth,role}){app.post('/api/maintenance/cleanup',auth,role('admin'),async(req,res)=>{
 if(req.body.confirmation!=='LIMPAR FROTA')return res.status(400).json({error:'Digite exatamente LIMPAR FROTA.'});
 const ticket=backupTickets.get(req.user.org);if(!ticket||ticket.user!==req.user.sub||ticket.checksum!==req.body.checksum||ticket.expires<Date.now())return res.status(409).json({error:'Gere e baixe um novo backup nesta página antes da limpeza.'});
 let c;try{c=await pool.connect();await c.query('BEGIN');await c.query("SET LOCAL lock_timeout='10s'");await c.query('LOCK TABLE '+TABLES.map(t=>'public.'+t).join(',')+' IN SHARE ROW EXCLUSIVE MODE');const user=(await c.query('SELECT name,email,role,active,password_hash FROM users WHERE id=$1 AND organization_id=$2',[req.user.sub,req.user.org])).rows[0];if(!user||!user.active||user.role!=='admin'||user.name!=='Michele Shibata'||user.email!=='michele@abccargas.local'||typeof req.body.password!=='string'||!(await bcrypt.compare(req.body.password,user.password_hash)))throw Error('Conta ou senha atual inválida.');if(ticket.expires<Date.now()||await stateDigest(c,req.user.org)!==ticket.digest)throw Error('O banco mudou desde o backup. Gere um novo backup.');await cleanRecords(c,req.user.org,req.user.sub);await c.query('COMMIT');backupTickets.delete(req.user.org);res.json({ok:true});}catch(e){if(c)await c.query('ROLLBACK').catch(()=>{});res.status(409).json({error:e.code==='55P03'?'Há operações em andamento. Tente após pausar o uso.':e.message});}finally{c?.release();}
});}
