import {PDFDocument} from 'pdfkit';
import sharp from 'sharp';
const slots={front:'Frontal',rear:'Traseira',left:'Lateral esquerda · motorista',right:'Lateral direita · passageiro',panel:'Painel · KM e combustível',detail1:'Avaria / detalhe 1',detail2:'Avaria / detalhe 2',detail3:'Avaria / detalhe 3'};
const status={pending:'Pendente',approved:'Aprovada',active:'Em utilização',reviewing:'Aguardando conferência',correction:'Correção solicitada',completed:'Concluída',rejected:'Recusada',cancelled:'Cancelada',draft:'Rascunho',submitted:'Enviada',returned:'Correção solicitada',accepted:'Aceita'};
const actions={requested:'Reserva solicitada',approve:'Reserva aprovada',reject:'Reserva recusada',cancel:'Reserva cancelada','request-correction':'Correção solicitada','approve-return':'Devolução aprovada','draft-checkin':'Rascunho da retirada','draft-checkout':'Rascunho da devolução','submitted-checkin':'Retirada confirmada','submitted-checkout':'Devolução enviada'};
const date=x=>x?new Date(x).toLocaleString('pt-BR',{timeZone:'America/Sao_Paulo'}):'Não informado';
export async function buildDossier(data){
 const doc=new PDFDocument({size:'A4',margin:42,bufferPages:true,info:{Title:'Dossiê da reserva',Author:'ABC Cargas'}}),chunks=[];
 const finished=new Promise((resolve,reject)=>{doc.on('data',b=>chunks.push(b));doc.on('end',()=>resolve(Buffer.concat(chunks)));doc.on('error',reject)});
 const r=data.reservation,v=data.vehicle,plate=r.vehicle_snapshot?.plate||v.plate,person=id=>data.people?.find(p=>p.id===id)?.name||id;
 const line=(label,value)=>{doc.font('Helvetica-Bold').fontSize(10).text(label+': ',{continued:true});doc.font('Helvetica').text(String(value??'Não informado')).moveDown(.4)};
 const heading=t=>doc.fillColor('#bb1830').font('Helvetica-Bold').fontSize(18).text(t).fillColor('#222222').font('Helvetica').fontSize(10).moveDown();
 heading('ABC Cargas · Dossiê da reserva');line('Placa',plate);line('Veículo',(r.vehicle_snapshot?.brand||v.details?.brand||'')+' '+(r.vehicle_snapshot?.model||v.model));line('Reserva',r.id);line('Situação',status[r.status]||r.status);line('Motorista',person(r.driver_id));line('Solicitante',person(r.requester_id));line('Retirada prevista',date(r.starts_at));line('Devolução prevista',date(r.ends_at));line('Finalidade',r.purpose);line('Destino',r.destination||'Não informado');line('Gerado em',date(new Date()));doc.moveDown().text('Horários de Brasília. Este documento reúne os registros disponíveis na emissão. Fotos registram o horário de envio, não necessariamente o horário de captura. Não constitui assinatura digital ou validação oficial de CNH.');
 const ins=data.inspections,initial=ins.find(i=>i.phase==='checkin'&&i.status==='accepted'),final=[...ins].reverse().find(i=>i.phase==='checkout'&&['accepted','submitted','returned'].includes(i.status));
 async function picture(photo,x,y,w,h){doc.rect(x,y,w,h).lineWidth(.5).strokeColor('#dddddd').stroke();if(!photo){doc.fillColor('#666666').fontSize(10).text('Foto não enviada',x+12,y+12,{width:w-24});return}const original=Buffer.isBuffer(photo.bytes)?photo.bytes:Buffer.from(photo.bytes,'base64');const buf=await sharp(original).rotate().jpeg({quality:88}).toBuffer();doc.image(buf,x,y,{fit:[w,h],align:'center',valign:'center'});doc.fillColor('#555555').fontSize(8).text('Enviada: '+date(photo.uploaded_at),x,y+h+8,{width:w});}
 function photo(i,slot){return i&&data.photos.find(p=>p.inspection_id===i.id&&p.slot===slot)}
 if(initial||final){for(const slot of ['front','rear','left','right','panel']){doc.addPage();heading('Comparação · '+slots[slot]);doc.fontSize(11).text('Retirada',42,105,{width:244}).text('Devolução',310,105,{width:244});await picture(photo(initial,slot),42,130,244,350);await picture(photo(final,slot),310,130,244,350);doc.x=42;doc.y=520;line('Placa',plate);line('Retirada',initial?date(initial.submitted_at):'Ainda não enviada');line('Devolução',final?date(final.submitted_at):'Ainda não enviada');}}
 for(const i of ins){doc.addPage();heading((i.phase==='checkin'?'Retirada':'Devolução')+' · '+(status[i.status]||i.status));line('Registro',i.id);line('Motorista / autor',person(i.author_id));line('Enviado em',date(i.submitted_at));line('Quilometragem',i.km===null?'Não informada':Number(i.km)+' km');line('Combustível',i.fuel===null?'Não informado':Number(i.fuel)+'%');line('Avarias',i.issue?'Sim':'Não informadas');line('Observações',i.notes||'Nenhuma');
 const photos=data.photos.filter(p=>p.inspection_id===i.id);for(const p of photos){doc.addPage();heading((i.phase==='checkin'?'Retirada':'Devolução')+' · '+(slots[p.slot]||p.slot));line('Registro / situação',i.id+' · '+(status[i.status]||i.status));await picture(p,42,160,511,440);doc.x=42;doc.y=640;line('SHA-256 do original',p.sha256);}}
 doc.addPage();heading('Histórico de decisões');for(const e of data.events){line(actions[e.action]||e.action,date(e.created_at)+' · '+(e.actor_name||person(e.actor_id)));if(e.note)doc.text(e.note,{width:511}).moveDown();}
 const range=doc.bufferedPageRange();for(let n=range.start;n<range.start+range.count;n++){doc.switchToPage(n);doc.fontSize(8).fillColor('#777777').text('ABC Cargas · '+plate+' · Página '+(n+1)+' de '+range.count,42,805,{lineBreak:false});}doc.end();return finished;
}
