import express from 'express';
import {requireDriver} from './driver-policy.js';
import {buildDossier} from './dossier.js';
import sharp from 'sharp';
import {createHash} from 'node:crypto';
import {pool,tx} from './db.js';
import {InputError} from './validation.js';
export const REQUIRED_SLOTS=['front','rear','left','right','panel'];
const SLOTS=[...REQUIRED_SLOTS,'detail1','detail2','detail3'];
export const managers=u=>['admin','manager'].includes(u.role);
const need=(ok,msg,status=400)=>{if(!ok)throw new InputError(msg,status)};
const uuid=x=>typeof x==='string'&&/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i.test(x);
const text=(x,max,required=false)=>{need(typeof x==='string'&&x.length<=max&&(!required||x.trim()),'Texto obrigatório ou muito longo.');return x.trim()};
export function interval(a,b){need(typeof a==='string'&&typeof b==='string'&&/[zZ]|[+-]\d\d:\d\d$/.test(a)&&/[zZ]|[+-]\d\d:\d\d$/.test(b),'Informe data e hora com fuso.');const start=new Date(a),end=new Date(b);need(Number.isFinite(+start)&&Number.isFinite(+end)&&end>start&&end-start<=90*86400000,'Período inválido: máximo de 90 dias.');return {start,end};}
export function photoType(bytes){if(!Buffer.isBuffer(bytes)||bytes.length<100)return null;if(bytes[0]===255&&bytes[1]===216&&bytes[2]===255)return 'image/jpeg';if(bytes.subarray(0,8).equals(Buffer.from([137,80,78,71,13,10,26,10])))return 'image/png';if(bytes.subarray(0,4).toString()==='RIFF'&&bytes.subarray(8,12).toString()==='WEBP')return 'image/webp';return null;}
export async function checkPhoto(bytes){const mime=photoType(bytes);need(mime,'Envie uma imagem JPEG, PNG ou WebP válida.');try{const image=sharp(bytes,{limitInputPixels:16000000});const m=await image.metadata();need(m.width>=64&&m.height>=64&&m.width<=4096&&m.height<=4096&&(!m.pages||m.pages===1),'Escolha uma foto estática entre 64 e 4096 pixels.');await image.stats();return mime;}catch(e){if(e instanceof InputError)throw e;throw new InputError('A imagem está danificada ou não pode ser lida. Selecione outra foto.');}}
async function lockOrg(c,u){await c.query('SELECT revision FROM organization_settings WHERE organization_id=$1 FOR UPDATE',[u.org]);}
async function bump(c,u){return Number((await c.query('UPDATE organization_settings SET revision=revision+1,updated_at=NOW() WHERE organization_id=$1 RETURNING revision',[u.org])).rows[0].revision);}
async function getReservation(c,u,id,lock=false){need(uuid(id),'Reserva inválida.');const {rows}=await c.query('SELECT * FROM fleet_reservations WHERE organization_id=$1 AND id=$2'+(lock?' FOR UPDATE':''),[u.org,id]);const r=rows[0];need(r,'Reserva não encontrada.',404);need(managers(u)||r.requester_id===u.sub||r.driver_id===u.sub,'Sem acesso a esta reserva.',403);return r;}
const driverOnly=(u,r)=>need(u.sub===r.driver_id,'A vistoria deve ser enviada pela conta do motorista designado.',403);
async function event(c,u,id,action,note=''){await c.query('INSERT INTO fleet_reservation_events(organization_id,reservation_id,action,actor_id,note) VALUES($1,$2,$3,$4,$5)',[u.org,id,action,u.sub,note]);}
async function conflicts(c,u,vehicle,start,end,exclude=null){const {rows}=await c.query(`SELECT id FROM fleet_reservations WHERE organization_id=$1 AND vehicle_code=$2 AND id IS DISTINCT FROM $5::uuid AND status IN ('pending','approved','active','reviewing','correction') AND (starts_at<$4 AND ends_at>$3 OR status IN ('active','reviewing','correction') AND ends_at<=NOW()) LIMIT 1`,[u.org,vehicle,start,end,exclude]);return rows.length>0;}
async function vehicle(c,u,code){const {rows}=await c.query('SELECT * FROM vehicles WHERE organization_id=$1 AND code=$2',[u.org,code]);need(rows[0],'Veículo não encontrado.',404);return rows[0];}
const serial=r=>({...r,version:Number(r.version)});
export async function listReservations(c,u){const {rows}=await c.query(`SELECT r.*,COALESCE(r.vehicle_snapshot->>'plate',v.plate) plate,COALESCE(r.vehicle_snapshot->>'model',v.model) model,COALESCE(r.vehicle_snapshot->>'brand',v.details->>'brand') brand,dr.name driver_name,rq.name requester_name FROM fleet_reservations r JOIN vehicles v ON v.organization_id=r.organization_id AND v.code=r.vehicle_code JOIN users dr ON dr.id=r.driver_id JOIN users rq ON rq.id=r.requester_id WHERE r.organization_id=$1 AND ($2::boolean OR r.driver_id=$3 OR r.requester_id=$3) ORDER BY r.starts_at DESC`,[u.org,managers(u),u.sub]);return rows.map(serial);}
export function installReservations(app,auth){
 const write=(req,_res,next)=>{need(req.user.role!=='viewer','Seu perfil permite apenas consulta.',403);next()};
 app.get('/api/reservations',auth,async(req,res)=>res.json({reservations:await listReservations(pool,req.user)}));
 app.get('/api/reservation-people',auth,async(req,res)=>{const {rows}=await pool.query(`SELECT id,name,email,role FROM users WHERE organization_id=$1 AND active=true AND role<>'viewer' AND ($2::boolean OR id=$3) ORDER BY name`,[req.user.org,managers(req.user),req.user.sub]);res.json({people:rows})});
 app.get('/api/reservations/availability',auth,async(req,res)=>{const {start,end}=interval(req.query.start,req.query.end);const {rows}=await pool.query(`SELECT v.code id,v.plate,v.model,v.details->>'yardId' "yardId",v.details->>'brand' brand FROM vehicles v WHERE organization_id=$1 AND COALESCE((details->>'active')::boolean,true)=true AND (status='Disponível' OR status='Em operação' AND EXISTS(SELECT 1 FROM fleet_reservations current_r WHERE current_r.organization_id=v.organization_id AND current_r.vehicle_code=v.code AND current_r.status IN ('active','reviewing','correction') AND current_r.ends_at<=$2 AND current_r.ends_at>NOW())) AND NOT EXISTS(SELECT 1 FROM fleet_reservations r WHERE r.organization_id=v.organization_id AND r.vehicle_code=v.code AND status IN ('pending','approved','active','reviewing','correction') AND (starts_at<$3 AND ends_at>$2 OR status IN ('active','reviewing','correction') AND ends_at<=NOW())) ORDER BY plate`,[req.user.org,start,end]);res.json({vehicles:rows})});
 app.post('/api/reservations',auth,write,async(req,res)=>{const u=req.user,b=req.body||{},{start,end}=interval(b.start,b.end);need(end>new Date()&&start>=new Date(Date.now()-60000),'A reserva deve começar agora ou no futuro.');const driver=managers(u)?b.driverId:u.sub;need(uuid(driver),'Selecione o motorista.');const purpose=text(b.purpose,500,true),destination=text(b.destination||'',300);const result=await tx(async c=>{await lockOrg(c,u);const v=await vehicle(c,u,b.vehicle);need(v.details?.active!==false,'Veículo inativo.',409);await requireDriver(c,u.org,driver);need(v.status!=='Indisponível','Este veículo está indisponível.',409);if(v.status==='Em operação'){const scheduled=await c.query("SELECT id FROM fleet_reservations WHERE organization_id=$1 AND vehicle_code=$2 AND status IN ('active','reviewing','correction') AND ends_at<=$3 AND ends_at>NOW()",[u.org,v.code,start]);need(scheduled.rowCount,'Veículo em operação sem liberação prevista para este período.',409);}need(!(await conflicts(c,u,v.code,start,end)),'O veículo já possui reserva ou devolução atrasada neste período.',409);const valid=await c.query("SELECT id FROM users WHERE organization_id=$1 AND id=$2 AND active=true AND role<>'viewer'",[u.org,driver]);need(valid.rowCount,'Motorista sem conta ativa.');const r=(await c.query(`INSERT INTO fleet_reservations(organization_id,vehicle_code,requester_id,driver_id,starts_at,ends_at,purpose,destination,vehicle_snapshot) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9) RETURNING *`,[u.org,v.code,u.sub,driver,start,end,purpose,destination,JSON.stringify({plate:v.plate,model:v.model,brand:v.details?.brand||''})])).rows[0];await event(c,u,r.id,'requested');return {reservation:serial(r),revision:await bump(c,u)}});res.status(201).json(result)});
 app.get('/api/reservations/:id',auth,async(req,res)=>{const u=req.user,r=await getReservation(pool,u,req.params.id);const [i,p,e]=await Promise.all([pool.query('SELECT * FROM fleet_inspections WHERE organization_id=$1 AND reservation_id=$2 ORDER BY created_at,id',[u.org,r.id]),pool.query(`SELECT p.id,p.inspection_id,p.slot,p.mime_type,p.sha256,p.uploaded_at,users.name uploaded_name FROM fleet_inspection_photos p JOIN fleet_inspections i ON i.id=p.inspection_id JOIN users ON users.id=p.uploaded_by WHERE p.organization_id=$1 AND i.reservation_id=$2 ORDER BY p.uploaded_at`,[u.org,r.id]),pool.query(`SELECT e.action,e.note,e.created_at,users.name actor_name FROM fleet_reservation_events e JOIN users ON users.id=e.actor_id WHERE e.organization_id=$1 AND reservation_id=$2 ORDER BY e.id`,[u.org,r.id])]);res.json({reservation:serial(r),inspections:i.rows.map(x=>({...x,km:x.km===null?null:Number(x.km),fuel:x.fuel===null?null:Number(x.fuel),photos:p.rows.filter(p=>p.inspection_id===x.id).map(p=>({...p,url:'/api/inspection-photos/'+p.id}))})),events:e.rows})});
 app.post('/api/reservations/:id/action',auth,write,async(req,res)=>{const u=req.user,b=req.body||{},result=await tx(async c=>{await lockOrg(c,u);const r=await getReservation(c,u,req.params.id,true);need(Number.isInteger(b.version)&&b.version===r.version,'A reserva mudou. Atualize antes de continuar.',409);let status=r.status,note=text(b.note||'',1500);switch(b.action){
 case 'approve':await requireDriver(c,u.org,r.driver_id);need((await vehicle(c,u,r.vehicle_code)).details?.active!==false,'Veículo inativo.',409);need(managers(u),'Apenas o responsável pode aprovar.',403);need(r.status==='pending','Reserva fora da etapa de aprovação.',409);need(new Date(r.ends_at)>new Date(),'O período da reserva já terminou.');need(!(await conflicts(c,u,r.vehicle_code,r.starts_at,r.ends_at,r.id)),'Conflito de horário.',409);need((await vehicle(c,u,r.vehicle_code)).status!=='Indisponível','Veículo indisponível.',409);status='approved';break;
 case 'reject':need(managers(u),'Apenas o responsável pode recusar.',403);need(r.status==='pending','Reserva fora da etapa de aprovação.',409);need(note,'Informe o motivo da recusa.');status='rejected';break;
 case 'cancel':need(managers(u)||r.requester_id===u.sub||r.driver_id===u.sub,'Sem permissão.',403);need(['pending','approved'].includes(r.status),'Não é possível cancelar uma utilização iniciada.',409);need(note,'Informe o motivo do cancelamento.');status='cancelled';break;
 case 'request-correction':need(managers(u),'Apenas o responsável pode conferir.',403);need(r.status==='reviewing','Devolução fora da etapa de conferência.',409);need(note,'Informe o que precisa ser corrigido.');status='correction';await c.query("UPDATE fleet_inspections SET status='returned' WHERE reservation_id=$1 AND phase='checkout' AND status='submitted'",[r.id]);break;
 case 'approve-return':need(managers(u),'Apenas o responsável pode liberar.',403);need(r.status==='reviewing','Devolução fora da etapa de conferência.',409);need(['Disponível','Indisponível'].includes(b.vehicleStatus),'Selecione a condição final do veículo.');const last=(await c.query("SELECT * FROM fleet_inspections WHERE reservation_id=$1 AND phase='checkout' AND status='submitted' ORDER BY submitted_at DESC LIMIT 1",[r.id])).rows[0];need(last,'Checkout não encontrado.');if(last.issue&&b.vehicleStatus==='Disponível')need(note,'Justifique a liberação do veículo com ocorrência.');await c.query("UPDATE fleet_inspections SET status='accepted' WHERE id=$1",[last.id]);await c.query('UPDATE vehicles SET status=$3,km=GREATEST(km,$4),fuel=$5,updated_at=NOW() WHERE organization_id=$1 AND code=$2',[u.org,r.vehicle_code,b.vehicleStatus,last.km,last.fuel]);status='completed';note=(note?note+' · ':'')+'Condição final: '+b.vehicleStatus;break;
 default:throw new InputError('Ação inválida.');}
 const row=(await c.query('UPDATE fleet_reservations SET status=$2,version=version+1,updated_at=NOW() WHERE id=$1 RETURNING *',[r.id,status])).rows[0];await event(c,u,r.id,b.action,note);return {reservation:serial(row),revision:await bump(c,u)}});res.json(result)});
 app.post('/api/reservations/:id/inspections',auth,write,async(req,res)=>{const u=req.user,phase=req.body.phase;need(['checkin','checkout'].includes(phase),'Etapa inválida.');const result=await tx(async c=>{await lockOrg(c,u);const r=await getReservation(c,u,req.params.id,true);driverOnly(u,r);if(phase==='checkin')await requireDriver(c,u.org,r.driver_id);need(phase==='checkin'?r.status==='approved':['active','correction'].includes(r.status),'Vistoria fora da etapa permitida.',409);let row=(await c.query("SELECT * FROM fleet_inspections WHERE reservation_id=$1 AND phase=$2 AND status='draft'",[r.id,phase])).rows[0];if(!row){row=(await c.query('INSERT INTO fleet_inspections(organization_id,reservation_id,phase,author_id) VALUES($1,$2,$3,$4) RETURNING *',[u.org,r.id,phase,u.sub])).rows[0];if(phase==='checkout'&&r.status==='correction'){const prior=(await c.query("SELECT id,km,fuel,notes,issue FROM fleet_inspections WHERE reservation_id=$1 AND phase='checkout' AND status='returned' ORDER BY submitted_at DESC LIMIT 1",[r.id])).rows[0];if(prior){const occupied=Number((await c.query('SELECT COALESCE(sum(octet_length(bytes)),0) size FROM fleet_inspection_photos WHERE organization_id=$1',[u.org])).rows[0].size),copied=Number((await c.query('SELECT COALESCE(sum(octet_length(bytes)),0) size FROM fleet_inspection_photos WHERE inspection_id=$1',[prior.id])).rows[0].size);need(occupied+copied<=Number(process.env.PHOTO_QUOTA_MB||250)*1024*1024,'Limite de armazenamento atingido. Avise o responsável.',413);await c.query('UPDATE fleet_inspections SET km=$2,fuel=$3,notes=$4,issue=$5 WHERE id=$1',[row.id,prior.km,prior.fuel,prior.notes,prior.issue]);await c.query(`INSERT INTO fleet_inspection_photos(organization_id,inspection_id,slot,mime_type,bytes,sha256,uploaded_by,uploaded_at) SELECT organization_id,$2,slot,mime_type,bytes,sha256,uploaded_by,uploaded_at FROM fleet_inspection_photos WHERE inspection_id=$1`,[prior.id,row.id]);}}await event(c,u,r.id,'draft-'+phase)}return {inspectionId:row.id}});res.json(result)});
 async function editable(c,u,id){need(uuid(id),'Vistoria inválida.');const row=(await c.query('SELECT * FROM fleet_inspections WHERE organization_id=$1 AND id=$2 FOR UPDATE',[u.org,id])).rows[0];need(row,'Vistoria não encontrada.',404);const r=await getReservation(c,u,row.reservation_id,true);driverOnly(u,r);need(row.status==='draft','Vistoria enviada não pode ser alterada.',409);need(row.phase==='checkin'?r.status==='approved':['active','correction'].includes(r.status),'A reserva mudou de etapa.',409);return {row,r};}
 app.put('/api/inspections/:id',auth,write,async(req,res)=>{const u=req.user,b=req.body||{};need(typeof b.km==='number'&&Number.isFinite(b.km)&&b.km>=0&&b.km<10000000&&typeof b.fuel==='number'&&Number.isFinite(b.fuel)&&b.fuel>=0&&b.fuel<=100,'KM ou combustível inválido.');need(typeof b.issue==='boolean','Informe se há avarias.');const notes=text(b.notes||'',2000);if(b.issue)need(notes,'Descreva as avarias.');await tx(async c=>{await lockOrg(c,u);const {row}=await editable(c,u,req.params.id);await c.query('UPDATE fleet_inspections SET km=$2,fuel=$3,notes=$4,issue=$5 WHERE id=$1',[row.id,b.km,b.fuel,notes,b.issue])});res.json({ok:true})});
 app.put('/api/inspections/:id/photos/:slot',auth,write,express.raw({type:['image/jpeg','image/png','image/webp'],limit:700000}),async(req,res)=>{const u=req.user,slot=req.params.slot;need(SLOTS.includes(slot),'Ângulo inválido.');const mime=await checkPhoto(req.body);need(mime&&mime===req.get('Content-Type'),'Envie uma imagem JPEG, PNG ou WebP válida.');const hash=createHash('sha256').update(req.body).digest('hex');const result=await tx(async c=>{await lockOrg(c,u);const {row,r}=await editable(c,u,req.params.id);const dup=await c.query(`SELECT p.id FROM fleet_inspection_photos p JOIN fleet_inspections i ON i.id=p.inspection_id WHERE i.reservation_id=$1 AND p.sha256=$2 AND (i.phase<>$3 OR i.id=$4 AND p.slot<>$5)`,[r.id,hash,row.phase,row.id,slot]);need(!dup.rowCount,'Use fotos diferentes para cada ângulo e para retirada/devolução.');const quota=Number(process.env.PHOTO_QUOTA_MB||250)*1024*1024;const size=Number((await c.query('SELECT COALESCE(sum(octet_length(bytes)),0) size FROM fleet_inspection_photos WHERE organization_id=$1',[u.org])).rows[0].size),old=Number((await c.query('SELECT octet_length(bytes) size FROM fleet_inspection_photos WHERE inspection_id=$1 AND slot=$2',[row.id,slot])).rows[0]?.size||0);need(size-old+req.body.length<=quota,'Limite de armazenamento de fotos atingido. Avise o responsável.',413);const p=(await c.query(`INSERT INTO fleet_inspection_photos(organization_id,inspection_id,slot,mime_type,bytes,sha256,uploaded_by) VALUES($1,$2,$3,$4,$5,$6,$7) ON CONFLICT(inspection_id,slot) DO UPDATE SET id=gen_random_uuid(),mime_type=EXCLUDED.mime_type,bytes=EXCLUDED.bytes,sha256=EXCLUDED.sha256,uploaded_by=EXCLUDED.uploaded_by,uploaded_at=NOW() RETURNING id`,[u.org,row.id,slot,mime,req.body,hash,u.sub])).rows[0];return {id:p.id,url:'/api/inspection-photos/'+p.id}});res.json(result)});
 app.post('/api/inspections/:id/submit',auth,write,async(req,res)=>{const u=req.user;need(req.body.confirm===true,'Confirme a vistoria antes de enviar.');const result=await tx(async c=>{await lockOrg(c,u);const {row,r}=await editable(c,u,req.params.id);need(row.km!==null&&row.fuel!==null,'Preencha quilometragem e combustível.');const photos=(await c.query('SELECT slot,sha256 FROM fleet_inspection_photos WHERE inspection_id=$1',[row.id])).rows;need(REQUIRED_SLOTS.every(s=>photos.some(p=>p.slot===s)),'Envie as cinco fotos obrigatórias.');need(new Set(photos.filter(p=>REQUIRED_SLOTS.includes(p.slot)).map(p=>p.sha256)).size===5,'Os cinco ângulos devem ter fotos diferentes.');const v=await vehicle(c,u,r.vehicle_code);let status;
 if(row.phase==='checkin'){await requireDriver(c,u.org,r.driver_id);need(v.details?.active!==false,'Veículo inativo.',409);need(new Date()>=new Date(new Date(r.starts_at).getTime()-30*60000)&&new Date()<new Date(r.ends_at),'A retirada é permitida a partir de 30 minutos antes do início e antes do fim da reserva.');need(v.status==='Disponível','O veículo ainda não está liberado para retirada.',409);const inUse=await c.query("SELECT id FROM fleet_reservations WHERE organization_id=$1 AND vehicle_code=$2 AND id<>$3 AND status IN ('active','reviewing','correction')",[u.org,r.vehicle_code,r.id]);need(!inUse.rowCount,'Existe utilização ou conferência pendente deste veículo.',409);need(Number(row.km)>=Number(v.km),'KM inicial menor que a quilometragem cadastrada.');await c.query("UPDATE vehicles SET status='Em operação',km=$3,fuel=$4,driver=$5,updated_at=NOW() WHERE organization_id=$1 AND code=$2",[u.org,r.vehicle_code,row.km,row.fuel,u.name]);status='active';}
 else {const start=(await c.query("SELECT km FROM fleet_inspections WHERE reservation_id=$1 AND phase='checkin' AND status='accepted' LIMIT 1",[r.id])).rows[0];need(start&&Number(row.km)>=Number(start.km)&&Number(row.km)>=Number(v.km),'KM final menor que o KM inicial ou atual.');await c.query("UPDATE vehicles SET status='Em operação',km=$3,fuel=$4,updated_at=NOW() WHERE organization_id=$1 AND code=$2",[u.org,r.vehicle_code,row.km,row.fuel]);status='reviewing';}
 await c.query('UPDATE fleet_inspections SET status=$2,submitted_at=NOW() WHERE id=$1',[row.id,row.phase==='checkin'?'accepted':'submitted']);const rr=(await c.query('UPDATE fleet_reservations SET status=$2,version=version+1,updated_at=NOW() WHERE id=$1 RETURNING *',[r.id,status])).rows[0];await event(c,u,r.id,'submitted-'+row.phase,row.issue?'Avarias registradas':'Sem avarias informadas');return {reservation:serial(rr),revision:await bump(c,u)}});res.json(result)});
 app.get('/api/inspection-photos/:id',auth,async(req,res)=>{need(uuid(req.params.id),'Foto inválida.');const u=req.user,p=(await pool.query(`SELECT p.*,i.reservation_id FROM fleet_inspection_photos p JOIN fleet_inspections i ON i.id=p.inspection_id WHERE p.organization_id=$1 AND p.id=$2`,[u.org,req.params.id])).rows[0];need(p,'Foto não encontrada.',404);await getReservation(pool,u,p.reservation_id);res.set({'Content-Type':p.mime_type,'Cache-Control':'private, no-store','X-Content-Type-Options':'nosniff','Content-Disposition':'inline'}).send(p.bytes)});
 app.get('/api/reservations/:id/dossier',auth,async(req,res)=>{const u=req.user;
 const data=await tx(async c=>{await c.query('SET TRANSACTION ISOLATION LEVEL REPEATABLE READ, READ ONLY');const r=await getReservation(c,u,req.params.id);const inspections=(await c.query('SELECT * FROM fleet_inspections WHERE organization_id=$1 AND reservation_id=$2 ORDER BY created_at,id',[u.org,r.id])).rows;
 const photos=(await c.query('SELECT p.* FROM fleet_inspection_photos p JOIN fleet_inspections i ON i.id=p.inspection_id WHERE p.organization_id=$1 AND i.reservation_id=$2 ORDER BY p.uploaded_at,p.slot',[u.org,r.id])).rows;
 const events=(await c.query('SELECT e.*,u.name actor_name FROM fleet_reservation_events e JOIN users u ON u.id=e.actor_id WHERE e.organization_id=$1 AND reservation_id=$2 ORDER BY e.id',[u.org,r.id])).rows;
 const people=(await c.query('SELECT id,name FROM users WHERE organization_id=$1 AND id=ANY($2::uuid[])',[u.org,[r.driver_id,r.requester_id]])).rows;return {schemaVersion:4,reservation:r,vehicle:await vehicle(c,u,r.vehicle_code),inspections,photos,events,people};});
 res.set('Cache-Control','no-store');if(req.query.format==='json')return res.json({...data,photos:data.photos.map(p=>({...p,bytes:p.bytes.toString('base64')}))});const pdf=await buildDossier(data);res.set({'Content-Type':'application/pdf','Content-Disposition':'attachment; filename="dossie-'+data.reservation.id+'.pdf"'}).send(pdf);
 });
}
